var res = {
   Title_png:"res/title.png",
   howtoplay_png:"res/howto_scene.png",
   help_png: "res/help1_scene.png",
   help2_png: "res/help2_scene.png",
   help3_png: "res/help3_scene.png",
   credit_png: "res/credit.png",
   gameover_png: "res/gameover_scene.png",
   clear_png: "res/clear_scene.png",
   player_png: "res/player.png",
   player_jump_png: "res/player_jump.png",
   player_idol_png: "res/player_idol.png",
   player_death_png: "res/player_death.png",
   terrain_png: "res/terrain.png",
   background_png: "res/glass2.png",
   background2_png: "res/forest.jpg",
   map00_tmx: "res/map00.tmx",
   map_test_tmx: "res/map_test.tmx",
   object_tsx: "res/object.tsx",
   terrain_tsx: "res/terrain.tsx",
   object_png: "res/object.png",
   pickup_coin_mp3: "res/se/coin.mp3",
   //food_mp3: "res/food.mp3",
   push_se:"res/se/kettei.mp3",
   heal_se:"res/se/heal.wav",
   bell_mp3:"res/se/tirin1.mp3",
   delete_mp3:"res/se/delete.wav",
   landing_mp3: "res/se/landing.mp3",
   jump_mp3: "res/se/food.mp3",
   decide_mp3: "res/se/decide.mp3",
   complete_mp3: "res/se/complete.mp3",
   start_mp3: "res/se/start.mp3",
   explode_mp3: "res/se/explode.mp3",
   damage_mp3: "res/se/damage.mp3",
   up_mp3: "res/se/up.mp3",
   book_open_mp3: "res/se/book_open.mp3",
   book_close_mp3: "res/se/book_close.mp3",
   page_mp3: "res/se/page.mp3",
   credit_in:"res/se/credit_in.mp3",
   credit_out:"res/se/credit_out.mp3",
   bgm1:"res/bgm/gauru.mp3",
   bgm2:"res/bgm/WildArms.mp3",
   bgm3:"res/bgm/bakemono.mp3",
   bgm5:"res/bgm/tasogare.wav",
   bgm6:"res/bgm/Flip_Flap.mp3",
   bgm7: "res/bgm/SQ4-2.mp3",
   bgm8: "res/bgm/irisu.mp3",
   fanfare:"res/bgm/win.wav"
};

var g_resources = [];
for (var i in res) {
   g_resources.push(res[i]);
}
